---
    name: Checks
    
    on: [push]
    
    jobs:
      test-lint:
        name: Test and lint
    
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2
        - name: Set up Python 3.11
          uses: actions/setup-python@v2
          with:
            python-version: 3.11
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        - name: Install dependencies for testing
          run: |
            if [ -f requirements-test.txt ]; then pip install -r requirements-test.txt; fi
        - name: Enforce black syntax
          run: |
            black --fast .
        - name: Lint with ruff
          run: |
            ruff check -v .
